export const REQUIRED = [
  {
    id: "req-1",
    title: "新進人員教育訓練 — 總部與國內行銷通路",
    badge: "series",
    status: "completed",
    date: "2026.03.23 15:07",
    enrolled: 39,
    comments: 0,
    likes: 5,
    desc: "兩天的入門訓練，包含公司文化、組織架構、總部走訪與通路觀察。",
    cover: "training",
    duration: "8h 20m",
    chapters: 12,
  },
];

export const LATEST = [
  {
    id: "c-1",
    title: "2026 年職務說明會",
    date: "2026.05.04 10:04",
    views: 173,
    comments: 0,
    likes: 0,
    desc: "年度職務調整、KPI 重點與部門協作流程說明。",
    cover: "job",
    tag: "HR",
    duration: "1h 12m",
    chapters: 5,
  },
  {
    id: "c-2",
    title: "個人資料保護指南",
    date: "2025.11.26 09:40",
    views: 197,
    comments: 0,
    likes: 0,
    desc: "ISO/IEC 27701 現代化隱私管理框架，蒐集、處理、利用三階段重點。",
    cover: "privacy",
    tag: "Compliance",
    duration: "55m",
    chapters: 6,
  },
  {
    id: "c-3",
    title: "企業誠信 — 反貪腐及反賄賂",
    date: "2025.07.21 15:09",
    views: 323,
    comments: 0,
    likes: 2,
    desc: "識別利益衝突情境、如何回報以及內外部稽核窗口流程。",
    cover: "ethics",
    tag: "Ethics",
    duration: "42m",
    chapters: 4,
  },
  {
    id: "c-4",
    title: "誠信經營守則",
    date: "2025.06.18 13:27",
    views: 186,
    comments: 0,
    likes: 2,
    desc: "公司治理、董事會運作與利害關係人溝通的核心守則。",
    cover: "governance",
    tag: "Governance",
    duration: "38m",
    chapters: 5,
  },
  {
    id: "c-5",
    title: "YOLO 演算法概論",
    date: "2026.04.29 12:00",
    views: 17,
    comments: 0,
    likes: 1,
    desc: "物件偵測模型架構、訓練資料準備與在產線檢測的應用案例。",
    cover: "yolo",
    tag: "AI / R&D",
    duration: "1h 30m",
    chapters: 8,
  },
  {
    id: "c-6",
    title: "優良文件規範 GDP",
    date: "2026.04.29 00:00",
    views: 11,
    comments: 0,
    likes: 0,
    desc: "Good Documentation Practice — 紀錄一致性、追溯性與簽核規範。",
    cover: "gdp",
    tag: "Quality",
    duration: "48m",
    chapters: 6,
  },
  {
    id: "c-7",
    title: "喬山 停薪留職管理辦法",
    date: "2026.04.29 15:11",
    views: 11,
    comments: 0,
    likes: 0,
    desc: "申請條件、年資計算、復職程序與相關 HR 表單填寫。",
    cover: "hr",
    tag: "HR",
    duration: "22m",
    chapters: 3,
  },
  {
    id: "c-8",
    title: "醫療器材上市認證原則",
    date: "2026.04.27 12:00",
    views: 12,
    comments: 0,
    likes: 0,
    desc: "TFDA 與 FDA 申報差異、510(k) 路徑、技術文件清單與時程。",
    cover: "medical",
    tag: "Regulatory",
    duration: "1h 05m",
    chapters: 7,
  },
];

export const MESSAGES = [
  { kind: "activity", text: "The Activities 給Joanne測試2 you registered will start tomorrow.", time: "2026.04.23 14:53", unread: true },
  { kind: "assign", text: "You have been assigned Activities 領導力工作坊 Q2", time: "2026.04.23 10:55", unread: true },
  { kind: "assign", text: "You have been assigned Activities ISO 內部稽核員培訓", time: "2026.04.22 15:19", unread: false },
  { kind: "register", text: "The Activities 給Joanne you registered are confirmed.", time: "2026.04.20 13:55", unread: false },
  { kind: "assign", text: "You have been assigned Activities 新版 ERP 操作說明", time: "2026.04.20 13:49", unread: false },
];

export const HISTORY = [
  { title: "LT8641UXE 介紹", time: "2026.04.20 15:34" },
  { title: "個人資料保護指南", time: "2026.04.20 15:16" },
  { title: "門市銷售 — 連鎖經營概念與戰略規劃", time: "2026.04.20 15:08" },
  { title: "如何使用 AI 工具提高工作效率", time: "2026.04.09 10:45" },
  { title: "新進人員教育訓練 — 總部與國內行...", time: "2026.03.23 16:18" },
];

export const NAV_ITEMS = [
  { id: "home", label: "首頁 Home", icon: "home" },
  { id: "courses", label: "課程 e-Courses", icon: "book", badge: 4 },
  { id: "activities", label: "活動 Activities", icon: "calendar" },
  { id: "exams", label: "測驗 Exams", icon: "exam" },
  { id: "survey", label: "問卷 Survey", icon: "survey" },
  { id: "library", label: "知識庫 Library", icon: "library" },
  { id: "messages", label: "訊息 Messages", icon: "bell", badge: 3 },
];

export const NAV_FOOT = [
  { id: "settings", label: "設定 Settings", icon: "settings" },
  { id: "profile", label: "個人 Profile", icon: "user" },
];
